_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 1
classes:
    value: 2
dropout:
    value: 0.5
epochs:
    value: 240
hidden_dim:
    value: 128
in_features:
    value: 7
learning_rate:
    value: 0.01
