_wandb:
    value:
        cli_version: 0.21.0
        e:
            y1xjvh0u01pc056836t6faqfibdonu8x:
                codePath: containers\ms-thesis-demo\ms-thesis-code\baseline-xgboost.py
                codePathLocal: baseline-xgboost.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "499256778752"
                        used: "398880034816"
                email: 99.oguz@gmail.com
                executable: C:\Users\Arslan\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
                git:
                    commit: b9172be7b9486a861d690cab7bcb4f29ad12f033
                    remote: https://github.com/Boysle/MS-Thesis-Oguz-Arslan.git
                gpu: NVIDIA GeForce RTX 3060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 4864
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3060 Ti
                      uuid: GPU-16f6c600-c32a-9b59-be76-280bbc899749
                host: Arslan-1
                memory:
                    total: "16794361856"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\Arslan\Desktop\MS-Thesis-Oguz-Arslan\containers\ms-thesis-demo\ms-thesis-code\baseline-xgboost.py
                python: CPython 3.13.7
                root: C:\Users\Arslan\Desktop\MS-Thesis-Oguz-Arslan\containers\ms-thesis-demo\ms-thesis-code
                startedAt: "2025-08-19T15:04:59.493744Z"
                writerId: y1xjvh0u01pc056836t6faqfibdonu8x
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 6
                - 53
            "2":
                - 1
                - 5
                - 6
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.7
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
checkpoint_dir:
    value: ./checkpoints_xgb
data_dir:
    value: E:\Raw RL Esports Replays\Day 3 Swiss Stage\Round 1\split_dataset
early_stopping_rounds:
    value: 50
learning_rate:
    value: 0.05
max_depth:
    value: 5
no_cuda:
    value: false
num_boost_round:
    value: 1000
run_name:
    value: null
wandb_project:
    value: rl-goal-prediction-xgboost
